version: "3.8"

volumes:
  data:

networks:
  analytics:
    driver: bridge

services:
  analytics-engine:
    image: ghcr.io/canner/analytics-engine:${ANALYTICS_ENGINE_VERSION}
    pull_policy: always
    platform: ${PLATFORM}
    ports:
      - ${ANALYTICS_ENGINE_SQL_PORT}:${ANALYTICS_ENGINE_SQL_PORT}
      - ${ANALYTICS_ENGINE_PORT}:${ANALYTICS_ENGINE_PORT}
    volumes:
      - ./etc:/usr/src/app/etc
    networks:
      - analytics

  ibis-server:
    image: ghcr.io/canner/analytics-engine-ibis:${IBIS_SERVER_VERSION}
    pull_policy: always
    platform: ${PLATFORM}
    ports:
      - ${IBIS_SERVER_PORT}:${IBIS_SERVER_PORT}
    environment:
      ANALYTICS_ENGINE_ENDPOINT: http://analytics-engine:${ANALYTICS_ENGINE_PORT}
      LOG_LEVEL: DEBUG
    networks:
      - analytics

  qdrant:
    image: qdrant/qdrant:v1.11.0
    pull_policy: always
    ports:
      - 6333:6333
      - 6334:6334
    networks:
      - analytics

  analytics-ui:
    image: ghcr.io/canner/analytics-ui:${ANALYTICS_UI_VERSION}
    pull_policy: always
    platform: ${PLATFORM}
    environment:
      DB_TYPE: sqlite
      # /app is the working directory in the container
      SQLITE_FILE: /app/data/db.sqlite3
      ANALYTICS_ENGINE_ENDPOINT: http://analytics-engine:${ANALYTICS_ENGINE_PORT}
      ANALYTICS_AI_ENDPOINT: http://host.docker.internal:${ANALYTICS_AI_SERVICE_PORT}
      IBIS_SERVER_ENDPOINT: http://ibis-server:${IBIS_SERVER_PORT}
      GENERATION_MODEL: ${GENERATION_MODEL}
      # telemetry
      ANALYTICS_ENGINE_PORT: ${ANALYTICS_ENGINE_PORT}
      ANALYTICS_AI_SERVICE_VERSION: ${ANALYTICS_AI_SERVICE_VERSION}
      ANALYTICS_UI_VERSION: ${ANALYTICS_UI_VERSION}
      ANALYTICS_ENGINE_VERSION: ${ANALYTICS_ENGINE_VERSION}
      USER_UUID: ${USER_UUID}
      POSTHOG_API_KEY: ${POSTHOG_API_KEY}
      POSTHOG_HOST: ${POSTHOG_HOST}
      TELEMETRY_ENABLED: ${TELEMETRY_ENABLED}
      # client side
      NEXT_PUBLIC_USER_UUID: ${USER_UUID}
      NEXT_PUBLIC_POSTHOG_API_KEY: ${POSTHOG_API_KEY}
      NEXT_PUBLIC_POSTHOG_HOST: ${POSTHOG_HOST}
      NEXT_PUBLIC_TELEMETRY_ENABLED: ${TELEMETRY_ENABLED}
      # configs
      ANALYTICS_PRODUCT_VERSION: ${ANALYTICS_PRODUCT_VERSION}

    ports:
      - ${ANALYTICS_UI_PORT}:3000
    volumes:
      - ./etc:/app/data
    networks:
      - analytics
    depends_on:
      - analytics-engine
      - ibis-server

  postgres:
    image: postgres:14-alpine
    platform: ${PLATFORM}
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - analytics
