apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-ai-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-ai-service
  template:
    metadata:
      labels:
        app: analytics-ai-service
    spec:
      containers:
        - name: analytics-ai-service
          image: ghcr.io/canner/analytics-ai-service:latest
          volumeMounts:
            - name: config-volume
              mountPath: /app/data
          env:
            - name: ANALYTICS_AI_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: analytics-config
                  key: ANALYTICS_AI_SERVICE_PORT
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: analyticsai-secrets
                  key: OPENAI_API_KEY
            - name: QDRANT_HOST
              valueFrom:
                configMapKeyRef:
                  name: analytics-config
                  key: QDRANT_HOST
            - name: LOGGING_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: analytics-config
                  key: LOGGING_LEVEL
            - name: ANALYTICS_UI_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: analytics-config
                  key: ANALYTICS_UI_ENDPOINT
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: LANGFUSE_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: analyticsai-secrets
                  key: LANGFUSE_PUBLIC_KEY
            - name: LANGFUSE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: analyticsai-secrets
                  key: LANGFUSE_SECRET_KEY
            - name: CONFIG_PATH
              value: /app/data/config.yaml
          ports:
            - containerPort: 5555
      volumes:
        - name: config-volume
          configMap:
            name: analytics-ai-service-config
            items:
              - key: config.yaml
                path: config.yaml
